name: "\U0001F41E Bug report"
description: Report an issue.
title: "[Bug]: "
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: reproduse
    attributes:
      label: To reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to ...
        2. Click on ...
        3. Scroll down to ..
        4. See error
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: What Browser are you using and on Which OS?
      placeholder: e.g. Google Chrome v109, Windows 10
    validations:
      required: true
  - type: checkboxes
    id: validation
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/CODE_OF_CONDUCT.md)
          required: true
        - label: Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.
          required: true
